-- MySQL Script generated by MySQL Workbench
-- Tue May 14 21:59:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `nomeDepartamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL,
  `NomeProf` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idProfessor`, `Departamento_idDepartamento`),
  INDEX `fk_Professor_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL,
  `nomeCurso` VARCHAR(45) NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `Departamento_idDepartamento`),
  INDEX `fk_Curso_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `nomeDisciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SolicitacaoPlanoSubstituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SolicitacaoPlanoSubstituicao` (
  `idPlanoDeAula` INT NOT NULL,
  `DataSolicitacao` DATE NOT NULL,
  `motivo` TEXT(100) NOT NULL,
  `ParecerCoordenacao` TEXT(100) NOT NULL,
  `Observacao` TEXT(100) NOT NULL,
  `Aprovado` TINYINT NOT NULL,
  `Professor_idProfessorRequerente` INT NOT NULL,
  `Professor_idProfessorSubstituto` INT NOT NULL,
  `Professor_idProfessorCoordenador` INT NOT NULL,
  PRIMARY KEY (`idPlanoDeAula`, `Professor_idProfessorRequerente`, `Professor_idProfessorSubstituto`, `Professor_idProfessorCoordenador`),
  INDEX `fk_SolicitacaoPlanoSubstituicao_Professor1_idx` (`Professor_idProfessorRequerente` ASC) VISIBLE,
  INDEX `fk_SolicitacaoPlanoSubstituicao_Professor2_idx` (`Professor_idProfessorSubstituto` ASC) VISIBLE,
  INDEX `fk_SolicitacaoPlanoSubstituicao_Professor3_idx` (`Professor_idProfessorCoordenador` ASC) VISIBLE,
  CONSTRAINT `fk_SolicitacaoPlanoSubstituicao_Professor1`
    FOREIGN KEY (`Professor_idProfessorRequerente`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitacaoPlanoSubstituicao_Professor2`
    FOREIGN KEY (`Professor_idProfessorSubstituto`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitacaoPlanoSubstituicao_Professor3`
    FOREIGN KEY (`Professor_idProfessorCoordenador`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AulasPlanoSubstituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AulasPlanoSubstituicao` (
  `idAulasPlanoSubstituicao` INT NOT NULL,
  `dataDaAula` DATE NOT NULL,
  `dataProposta` DATE NOT NULL,
  `horarioProposto` TIME NULL,
  `SolicitacaoPlanoSubstituicao_idPlanoDeAula` INT NOT NULL,
  `SolicitacaoPlanoSubstituicao_Professor_idProfessorSubstituto` INT NOT NULL,
  PRIMARY KEY (`idAulasPlanoSubstituicao`, `SolicitacaoPlanoSubstituicao_idPlanoDeAula`, `SolicitacaoPlanoSubstituicao_Professor_idProfessorSubstituto`),
  INDEX `fk_AulasPlanoSubstituicao_SolicitacaoPlanoSubstituicao1_idx` (`SolicitacaoPlanoSubstituicao_idPlanoDeAula` ASC, `SolicitacaoPlanoSubstituicao_Professor_idProfessorSubstituto` ASC) VISIBLE,
  CONSTRAINT `fk_AulasPlanoSubstituicao_SolicitacaoPlanoSubstituicao1`
    FOREIGN KEY (`SolicitacaoPlanoSubstituicao_idPlanoDeAula` , `SolicitacaoPlanoSubstituicao_Professor_idProfessorSubstituto`)
    REFERENCES `mydb`.`SolicitacaoPlanoSubstituicao` (`idPlanoDeAula` , `Professor_idProfessorSubstituto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `idSala` INT NOT NULL,
  `codigoSala` VARCHAR(45) NOT NULL,
  `bloco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `idTurma` INT NOT NULL,
  `nomeTurma` VARCHAR(45) NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  `Sala_idSala` INT NOT NULL,
  PRIMARY KEY (`idTurma`, `Curso_idCurso`, `Disciplina_idDisciplina`, `Sala_idSala`),
  INDEX `fk_Turma_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  INDEX `fk_Turma_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  INDEX `fk_Turma_Sala1_idx` (`Sala_idSala` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `mydb`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
